config/routes.rb
Rails.application.routes.draw do
  resources :scafs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #get '/' => 'home#index' : /로 접속을하면 home controller 안에 있는 index로 작업을 하라고 함.
  #action과 url을 연결하기
  get '/index' => 'home#index'
  get '/add' => 'calculator#add'

  post '/result' => 'calculator#result'
  #input name을 가져와서 사용할 수 있다.
  get '/result/:first/:second' => 'calculator#result'

  get '/read/index' => 'read_home#index'
  get '/read/write' => 'read_home#write'
  post '/read/create' => 'read_home#create'
  #:으로 params 받아오기
  get '/read/modify/:post_id' => 'read_home#modify'
  post '/read/update/:post_id' => 'read_home#update'
  get '/read/delete/:post_id' => 'read_home#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/scaf.rb
#rails g scaffold 모델이름 속성:타입 속성:타입 > 기본적인 CRUD 파일들이 생성됨
class Scaf < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #post 방식으로 전달 시 유효하지 않은 토큰 에러 안나게 임시로 작성하는 것
    skip_forgery_protection
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
    #add라는 action 만들기
    def add 
        @message = "Hello I'm information"
    end
    def result
        #@result = params[:first] + params[:second] -> 문자열로 됨!!
        @result = params[:first].to_i + params[:second].to_i #정수형 계산
    end
end

app/controllers/home_controller.rb
#Controller 만드는 법 : rails generate controller <컨트롤러 이름>
class HomeController < ApplicationController
    def index

    end
end

app/controllers/read_home_controller.rb
class ReadHomeController < ApplicationController
    def index
        @posts = Post.all
    end

    def write

    end

    def create
        #정보를 저장하는 기본 명령어
        post = Post.new
        post.title = params[:title]
        post.content = params[:content]
        post.save

        #다른 페이지로 이동시키기
        redirect_to '/read/index'
    end

    def modify
        #Post.all과 다르게 하나만 가져옴
        @post = Post.find(params[:post_id])
    end

    def update
        #한 데이터의 정보를 수정하여 업데이트하는 기본 명령어
        post = Post.find(params[:post_id])
        post.title = params[:title]
        post.content = params[:content]
        post.save
        redirect_to '/read/index'
    end

    def delete
        #한 데이터를 삭제하기
        Post.destroy(params[:post_id])
        #뒤로 가기 redirect_back(구 버전: redirect_to :back)
        redirect_to '/read/index'
    end
end

app/controllers/scafs_controller.rb
class ScafsController < ApplicationController
  before_action :set_scaf, only: %i[ show edit update destroy ]

  # GET /scafs or /scafs.json
  def index
    @scafs = Scaf.all
  end

  # GET /scafs/1 or /scafs/1.json
  def show
  end

  # GET /scafs/new
  def new
    @scaf = Scaf.new
  end

  # GET /scafs/1/edit
  def edit
  end

  # POST /scafs or /scafs.json
  def create
    @scaf = Scaf.new(scaf_params)

    respond_to do |format|
      if @scaf.save
        format.html { redirect_to @scaf, notice: "Scaf was successfully created." }
        format.json { render :show, status: :created, location: @scaf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scafs/1 or /scafs/1.json
  def update
    respond_to do |format|
      if @scaf.update(scaf_params)
        format.html { redirect_to @scaf, notice: "Scaf was successfully updated." }
        format.json { render :show, status: :ok, location: @scaf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scafs/1 or /scafs/1.json
  def destroy
    @scaf.destroy
    respond_to do |format|
      format.html { redirect_to scafs_url, notice: "Scaf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scaf
      @scaf = Scaf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scaf_params
      params.require(:scaf).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/read_home_helper.rb
module ReadHomeHelper
end

app/helpers/scafs_helper.rb
module ScafsHelper
end

app/views/calculator/add.erb
<%#add라는 함수의 변수를 사용할 수 있다.%>
<%# method post: 안보이게 할 것. get: 주소에 보일 것 action: 보내는 위치%>
<form method="post" action="/result">
    <input type="number" name="first"> +
    <input type="number" name="second">
    <input type="submit"/>
</form>
<br>
<%#URL을 이용한 방식%>
<a href="/result/1/1">1더하기 1의 결과</a>
<a href="/result?first=1&second=1">1더하기 1의 결과</a>

app/views/calculator/result.erb
결과 : <%= @result %>

app/views/home/index.erb
<a href="https://www.google.com">hello world</a>
<%#루비 문법을 넣을 수 있음%>
<% if true %>
    <%#루비는 var라던가 string같은 것을 사용하지 않고 변수를 파이썬처럼 만든다%>
    <% str = 'hahaha' %>
    <%= str %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/read_home/index.erb
<% @posts.each do |post| %>
    <%# post.id는 자동으로 생성된 id 값을 가져옴 %>
    제목 : <%= post.title %> <a href="/read/modify/<%= post.id %>">수정하기</a><br>
    내용 : <%= post.content %> <a href="/read/delete/<%= post.id %>">삭제하기</a>
    <hr>
<% end %>
<br>
<a href= "/read/write">글쓰러가기</a>

app/views/read_home/modify.erb
<form action="/read/update/<%= @post.id %>" method="post">
    제목 : <input type="text" name="title" value="<%= @post.title %>"/><br>
    내용 : <input type="text" name="content" value="<%= @post.content %>"/>
    <input type="submit"/>
</form>
<a href="/read/index">뒤로 돌아가기</a>

app/views/read_home/write.erb
<form action="/read/create" method="post">
    제목 : <input type="text" name="title"/><br>
    내용 : <input type="text" name="content"/>
    <input type="submit"/>
</form>
<a href="/read/index">뒤로 돌아가기</a>

app/views/scafs/_form.html.erb
<%= form_with(model: scaf) do |form| %>
  <% if scaf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scaf.errors.count, "error") %> prohibited this scaf from being saved:</h2>

      <ul>
        <% scaf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scafs/edit.html.erb
<h1>Editing Scaf</h1>

<%= render 'form', scaf: @scaf %>

<%= link_to 'Show', @scaf %> |
<%= link_to 'Back', scafs_path %>

app/views/scafs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scafs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scafs.each do |scaf| %>
      <tr>
        <td><%= scaf.title %></td>
        <td><%= scaf.content %></td>
        <td><%= link_to 'Show', scaf %></td>
        <td><%= link_to 'Edit', edit_scaf_path(scaf) %></td>
        <td><%= link_to 'Destroy', scaf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scaf', new_scaf_path %>

app/views/scafs/new.html.erb
<h1>New Scaf</h1>

<%= render 'form', scaf: @scaf %>

<%= link_to 'Back', scafs_path %>

app/views/scafs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scaf.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @scaf.content %>
</p>

<%= link_to 'Edit', edit_scaf_path(@scaf) %> |
<%= link_to 'Back', scafs_path %>